FROM armhf/debian:buster

# install java on image
RUN apt-get update
RUN apt-get install -y python3-pip npm
RUN pip install --no-cache-dir --upgrade pip
RUN pip install RPi.GPIO Adafruit_DHT smbus2 telepot

#setting up a new user
RUN useradd -ms /bin/bash  smartpot
USER smartpot
WORKDIR /home/smartpot

#setting up smartpot directory
COPY SmartPot ./SmartPot
COPY monitor.py .
COPY smartpot.log .
COPY smartpot.ini .
COPY TelegramSmartpot.py .

CMD python3 TelegramSmartpot.py