FROM arm32v7/debian:buster

# install java on image
RUN apt-get update
RUN apt-get install -y python3-pip npm
RUN apt-get install -y curl
RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install RPi.GPIO Adafruit_DHT smbus2 telepot
RUN  apt-get install -y  sudo apt-utils procps
RUN apt-get install -y systemd

#setting up a new user
RUN useradd -ms /bin/bash  smartpot
RUN usermod -aG sudo smartpot
USER smartpot
WORKDIR /home/smartpot
ENV TERM=xterm-256color

#setting up smartpot directory
COPY SmartPot ./SmartPot
COPY monitor.py .
COPY smartpot.log .
COPY smartpot.ini .
COPY TelegramSmartpot.py .

#Instatllation Node-Red
USER root
RUN curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered > nodered_install
RUN chmod a+x nodered_install
RUN ./nodered_install --node16 --confirm-root --confirm-install --nodered-user=smartpot --confirm-pi
USER smartpot
WORKDIR /home/smartpot
USER root
RUN systemctl enable nodered.service
RUN systemctl start nodered.service
RUN systemctl stop nodered.service
USER smartpot
RUN cd .node-red
RUN npm install i node-red-dashboard
RUN cd ..
USER smartpot
#auskommentieren von der ui
RUN sed -i -e "s/\/\/ui: { path: \"ui\" }/ui: { path: \"ui\" }/g"  ~/.node-red/settings.js
#RUN systemctl enable nodered.service

CMD python3 TelegramSmartpot.py
