FROM python:3.7-buster
# install java on image
RUN apt-get update 
RUN apt-get install -y python3-pip
RUN pip3 install RPi.GPIO Adafruit_DHT smbus2 telepot
RUN useradd -ms /bin/bash smartpot
USER smartpot
WORKDIR /home/smartpot

#setting up smartpot directory
RUN mkdir src
COPY src/SmartPot ./src/SmartPot
COPY src/monitor.py ./src
COPY src/logging_conf_setup.py ./src
COPY smartpot.log .
COPY smartpot.ini .
COPY telegram_smartpot.py .

RUN touch data.csv

CMD ["python","-u","telegram_smartpot.py"]
