FROM python:3.7-buster
# install java on image
RUN apt-get update 
RUN apt-get install -y python3-pip
RUN pip3 install RPi.GPIO Adafruit_DHT smbus2 telepot
RUN useradd -ms /bin/bash smartpot
USER smartpot
WORKDIR /home/smartpot

#setting up smartpot directory
COPY SmartPot ./SmartPot
COPY monitor.py .
COPY smartpot.log .
COPY smartpot.ini .
COPY logging_conf_setup.py .
COPY TelegramSmartpot.py .

RUN touch Logging.csv

CMD ["python","-u","TelegramSmartpot.py"]
